### ISSUE TITLE
InvocationTargetException should not be shown to user, the root cause should.

### ISSUE THREAD

**Issue by jackhatedance** [jackhatedance/plum#293]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.abstractfactory.plum.interaction.AbstractSimpleInteraction.invokeMethod(AbstractSimpleInteraction.java:99)
	... 15 more
Caused by: java.lang.RuntimeException: 无法关闭订单，状态不正确
	at com.enniu.rpd.paysina.service.impl.UserAccountTransferTransactionalServiceImpl.closeOrder(UserAccountTransferTransactionalServiceImpl.java:307)

**Comment by jackhatedance** [comment]
solution: re-throw its cause instead of InvocationTargetException
